import { Download, Edit3, FileText, Plus, Trash2 } from 'lucide-react'
import { FormEvent, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Card, Confirm, Empty, Field, FormActions, Loading, Modal, PageHeader, SearchInput, Status } from '../components/ui'
import { useAsync } from '../hooks/useAsync'
import { brl, toCents } from '../utils/format'
import { effectiveSalaryCents, salarySourceLabel } from '../utils/payroll-values'
import { ROUTES } from '../routes/registry'

export default function EmployeesPage(){
 const navigate=useNavigate(),employees=useAsync(()=>window.fluxoDre.funcionarios.list(),[]),cargos=useAsync(()=>window.fluxoDre.cargos.list(),[]),companies=useAsync(()=>window.fluxoDre.empresas.list(),[])
 const [search,setSearch]=useState(''),[form,setForm]=useState<any>(null),[remove,setRemove]=useState<any>(null)
 const rows=useMemo(()=>{const q=search.toLowerCase().trim();return employees.data?.filter((x:any)=>!q||String(x.nome||'').toLowerCase().includes(q)||String(x.cpf||'').replace(/\D/g,'').includes(q.replace(/\D/g,'')))||[]},[employees.data,search]),active=rows.filter((x:any)=>x.status==='ativo'),inactive=rows.filter((x:any)=>x.status!=='ativo')
 const cargoFor=(employee:any)=>cargos.data?.find((cargo:any)=>cargo.id===employee.cargo_id)
 const salaryFor=(employee:any)=>effectiveSalaryCents(employee,cargoFor(employee))
 const payroll=active.reduce((sum:any,employee:any)=>sum+salaryFor(employee),0)
 const submit=async(e:FormEvent)=>{e.preventDefault();await window.fluxoDre.funcionarios.save({...form,empresa_id:form.empresa_id?Number(form.empresa_id):null,cargo_id:form.cargo_id?Number(form.cargo_id):null,salario_centavos:toCents(form.salario)});setForm(null);employees.reload()}
 const table=(items:any[])=><div className="table-wrap"><table className="data-table"><thead><tr><th>Nome</th><th>CPF</th><th>Cargo</th><th>Empresa</th><th>Departamento</th><th className="number">Salário-base efetivo</th><th>Status</th><th></th></tr></thead><tbody>{items.map((x:any)=><tr key={x.id}><td><div className="employee-name"><span className="avatar">{x.nome.slice(0,1).toUpperCase()}</span><strong>{x.nome}</strong></div></td><td>{x.cpf||'Completar cadastro'}</td><td>{cargos.data?.find((c:any)=>c.id===x.cargo_id)?.nome||'Não definido'}</td><td>{companies.data?.find((c:any)=>c.id===x.empresa_id)?.nome_fantasia||'—'}</td><td>{x.departamento||'—'}</td><td className="number"><strong>{brl(salaryFor(x))}</strong><small>{salarySourceLabel(x,cargoFor(x))}</small></td><td><Status value={x.status}/></td><td><div className="row-actions"><button className="icon-button" title="Gerar documentos" onClick={()=>navigate(`${ROUTES.rhAdmissions}?id=${x.id}`)}><FileText size={15}/></button><button className="icon-button" onClick={()=>setForm({...x,salario:(x.salario_centavos/100).toFixed(2).replace('.',',')})}><Edit3 size={15}/></button><button className="icon-button" onClick={()=>setRemove(x)}><Trash2 size={15}/></button></div></td></tr>)}</tbody></table></div>
 return <><PageHeader title="Funcionários" description={`${active.length} ativos · Salários-base efetivos ${brl(payroll)}/mês`} actions={<><Button variant="secondary" icon={<Download size={16}/>}>Relatório</Button><Button icon={<Plus size={16}/>} onClick={()=>navigate(ROUTES.rhAdmissions)}>Novo funcionário</Button></>}/><div className="toolbar"><SearchInput value={search} onChange={setSearch} placeholder="Buscar por nome ou CPF..."/></div>{employees.loading?<Card><Loading/></Card>:rows.length?<><Card><div className="card-header"><h2>Ativos ({active.length})</h2><strong style={{fontSize:11,color:'#697488'}}>Salários-base efetivos: {brl(payroll)}/mês</strong></div>{active.length?table(active):<Empty title="Nenhum funcionário ativo"/>}</Card>{inactive.length>0&&<Card style={{marginTop:14} as any}><div className="card-header"><h2>Inativos ({inactive.length})</h2></div>{table(inactive)}</Card>}</>:<Card><Empty title="Nenhum funcionário cadastrado" description="Use Registro Funcionário para cadastrar e gerar o dossiê admissional." action={<Button onClick={()=>navigate(ROUTES.rhAdmissions)}>Registrar funcionário</Button>}/></Card>}<Modal open={!!form} title="Editar funcionário" onClose={()=>setForm(null)}><form onSubmit={submit}><div className="modal-body form-grid"><Field label="Nome completo" wide required><input required value={form?.nome||''} onChange={(e)=>setForm({...form,nome:e.target.value})}/></Field><Field label="CPF"><input value={form?.cpf||''} onChange={(e)=>setForm({...form,cpf:e.target.value})}/></Field><Field label="Cargo"><select value={form?.cargo_id||''} onChange={(e)=>setForm({...form,cargo_id:e.target.value})}><option value="">Selecione</option>{cargos.data?.map((x:any)=><option value={x.id} key={x.id}>{x.nome}</option>)}</select></Field><Field label="Empresa"><select value={form?.empresa_id||''} onChange={(e)=>setForm({...form,empresa_id:e.target.value})}><option value="">Selecione</option>{companies.data?.map((x:any)=><option value={x.id} key={x.id}>{x.nome_fantasia||x.razao_social}</option>)}</select></Field><Field label="Salário individual"><input value={form?.salario||''} placeholder="Em branco usa o salário do cargo" onChange={(e)=>setForm({...form,salario:e.target.value})}/></Field><Field label="Status"><select value={form?.status||'ativo'} onChange={(e)=>setForm({...form,status:e.target.value})}><option value="ativo">Ativo</option><option value="afastado">Afastado</option><option value="inativo">Inativo</option></select></Field></div><FormActions onCancel={()=>setForm(null)}/></form></Modal><Confirm open={!!remove} title="Inativar funcionário" description="O cadastro e os documentos serão preservados; o funcionário deixará de aparecer como ativo." danger onCancel={()=>setRemove(null)} onConfirm={async()=>{await window.fluxoDre.funcionarios.save({...remove,status:'inativo'});setRemove(null);employees.reload()}}/></>
}
