import { ArrowLeft, ArrowRight, CheckCircle2, FileSignature, FolderOpen, Printer, Save } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useSearchParams } from 'react-router-dom'
import { Button, Card, Field, Loading, PageHeader } from '../components/ui'
import { useAsync } from '../hooks/useAsync'
import { brl, toCents, today } from '../utils/format'

const steps=['Cadastro','Documentos e endereço','Contrato','Benefícios e EPI','Documentos']
const docs=[['contrato_experiencia','Contrato de experiência'],['ficha_registro','Ficha de registro'],['ordem_servico','Ordem de serviço'],['vale_transporte','Vale-transporte'],['ficha_epi','Ficha de EPI'],['carta_sindical','Carta de oposição sindical']]
const initial:any={
  nome:'',cpf:'',rg:'',rg_emissao:'',rg_orgao:'',data_nascimento:'',naturalidade:'',nacionalidade:'Brasileira',estado_civil:'',sexo:'',cor:'',escolaridade:'',deficiencia:'',pai:'',mae:'',
  ctps:'',ctps_serie:'',ctps_uf:'',ctps_expedicao:'',pis:'',cnh:'',cnh_categoria:'',titulo_eleitor:'',titulo_eleitor_zona:'',titulo_eleitor_secao:'',certificado_reservista:'',reservista_categoria:'',
  telefone:'',email:'',endereco:'',endereco_logradouro:'',endereco_numero:'',endereco_complemento:'',endereco_bairro:'',endereco_cidade:'',endereco_uf:'',cep:'',
  empresa_id:'',obra_atual_id:'',cargo_id:'',departamento:'',admissao:today(),salario:'',status:'ativo',banco:'',agencia:'',conta_bancaria:'',pix:'',matricula:'',matricula_esocial:'',fgts_optante:1,fgts_opcao_em:'',beneficiarios:'',
  jornada_inicio:'08:00',intervalo_inicio:'12:00',intervalo_fim:'13:00',jornada_fim:'17:00',experiencia_dias:45,experiencia_fim:'',vale_transporte_opcao:1,vale_transporte_detalhes:'',observacoes:'',
  selectedDocs:docs.filter(([key])=>key!=='carta_sindical').map(([key])=>key),selectedEpis:[]
}

export default function EmployeeRegistrationPage(){
  const [params]=useSearchParams(), id=params.get('id')
  const [step,setStep]=useState(0),[form,setForm]=useState<any>(initial),[saving,setSaving]=useState(false),[result,setResult]=useState<any>(null),[message,setMessage]=useState('')
  const companies=useAsync(()=>window.fluxoDre.empresas.list(),[]), works=useAsync(()=>window.fluxoDre.obras.list(),[]), catalog=useAsync(()=>window.fluxoDre.catalogo.list(),[]), epis=useAsync(()=>window.fluxoDre.epis.list(),[])

  useEffect(()=>{if(id)window.fluxoDre.funcionarios.get(Number(id)).then(employee=>employee&&setForm({...initial,...employee,salario:(employee.salario_centavos/100).toFixed(2).replace('.',',')}))},[id])
  useEffect(()=>{if(form.admissao){const date=new Date(`${form.admissao}T12:00:00`);date.setDate(date.getDate()+Number(form.experiencia_dias||45)-1);setForm((current:any)=>({...current,experiencia_fim:date.toISOString().slice(0,10),fgts_opcao_em:current.fgts_opcao_em||current.admissao}))}},[form.admissao,form.experiencia_dias])
  useEffect(()=>{if(epis.data?.length&&!form.selectedEpis.length)setForm((current:any)=>({...current,selectedEpis:epis.data!.map((item:any)=>item.id)}))},[epis.data])

  const set=(key:string,value:any)=>setForm((current:any)=>({...current,[key]:value}))
  const activeCargos=catalog.data?.cargos.filter((item:any)=>item.ativo)||[]
  const chosenCargo=catalog.data?.cargos.find((item:any)=>item.id===Number(form.cargo_id))
  const chosenBenefits=(catalog.data?.links||[]).filter((link:any)=>link.cargo_id===chosenCargo?.id&&link.ativo).map((link:any)=>({...link,benefit:catalog.data.beneficios.find((item:any)=>item.id===link.beneficio_id)}))
  const chooseCargo=(value:string)=>{const cargo=activeCargos.find((item:any)=>item.id===Number(value));setForm((current:any)=>({...current,cargo_id:value,salario:cargo?(cargo.salario_base_centavos/100).toFixed(2).replace('.',','):''}))}
  const validateIdentity=()=>{const fullName=String(form.nome||'').trim().split(/\s+/).filter(Boolean).length>=2,cpfDigits=String(form.cpf||'').replace(/\D/g,'');if(!fullName)return'Informe o nome completo do colaborador.';if(cpfDigits.length!==11)return'Informe um CPF válido com 11 dígitos.';return''}

  const saveEmployee=async()=>{
    const identityError=validateIdentity();if(identityError)throw new Error(identityError)
    setSaving(true)
    try{
      const employee=await window.fluxoDre.funcionarios.save({...form,empresa_id:form.empresa_id?Number(form.empresa_id):null,obra_atual_id:form.obra_atual_id?Number(form.obra_atual_id):null,cargo_id:form.cargo_id?Number(form.cargo_id):null,salario_centavos:toCents(form.salario),vale_transporte_opcao:Number(form.vale_transporte_opcao),fgts_optante:Number(form.fgts_optante)})
      setForm((current:any)=>({...current,id:employee.id}));return employee
    }finally{setSaving(false)}
  }
  const next=()=>{if(step===0){const error=validateIdentity();if(error)return setMessage(error)}if(step===2&&(!form.empresa_id||!form.cargo_id))return setMessage('Selecione empresa e cargo.');setMessage('');setStep(Math.min(4,step+1))}
  const generate=async()=>{setSaving(true);setMessage('');try{const employee=await saveEmployee();for(const epiId of form.selectedEpis)await window.fluxoDre.funcionarioEpis.save({funcionario_id:employee.id,epi_id:Number(epiId),data_entrega:form.admissao||today(),quantidade:1});setResult(await window.fluxoDre.documentos.generate({funcionario_id:employee.id,includeCarta:form.selectedDocs.includes('carta_sindical'),selected:form.selectedDocs}))}catch(error:any){setMessage(error.message)}finally{setSaving(false)}}

  const content=useMemo(()=>{
    if(step===0)return <><h3 className="section-title">Identificação do colaborador</h3><div className="form-grid form-grid-3">
      <div className="form-section-label field-wide"><strong>Identificação</strong><span>Dados básicos do colaborador.</span></div><Field label="Nome completo" required wide><input value={form.nome} onChange={e=>set('nome',e.target.value)}/></Field><Field label="CPF" required><input value={form.cpf} onChange={e=>set('cpf',e.target.value)}/></Field><Field label="Nascimento"><input type="date" value={form.data_nascimento} onChange={e=>set('data_nascimento',e.target.value)}/></Field>
      <div className="form-section-label field-wide"><strong>Dados pessoais</strong><span>Informações complementares para o cadastro trabalhista.</span></div><Field label="Estado civil"><select value={form.estado_civil} onChange={e=>set('estado_civil',e.target.value)}><option value="">Selecione</option><option>Solteiro(a)</option><option>Casado(a)</option><option>União estável</option><option>Divorciado(a)</option><option>Viúvo(a)</option></select></Field><Field label="Naturalidade"><input value={form.naturalidade} onChange={e=>set('naturalidade',e.target.value)}/></Field><Field label="Nacionalidade"><input value={form.nacionalidade} onChange={e=>set('nacionalidade',e.target.value)}/></Field>
      <Field label="Sexo"><select value={form.sexo} onChange={e=>set('sexo',e.target.value)}><option value="">Selecione</option><option value="feminino">Feminino</option><option value="masculino">Masculino</option><option value="outro">Outro</option><option value="nao_informado">Prefere não informar</option></select></Field><Field label="Cor / raça"><select value={form.cor} onChange={e=>set('cor',e.target.value)}><option value="">Selecione</option><option>Branca</option><option>Preta</option><option>Parda</option><option>Amarela</option><option>Indígena</option><option>Não informada</option></select></Field><Field label="Escolaridade"><select value={form.escolaridade} onChange={e=>set('escolaridade',e.target.value)}><option value="">Selecione</option><option>Fundamental incompleto</option><option>Fundamental completo</option><option>Médio incompleto</option><option>Médio completo</option><option>Superior incompleto</option><option>Superior completo</option><option>Pós-graduação</option></select></Field>
      <div className="form-section-label field-wide"><strong>Contato e informações complementares</strong><span>Dados para comunicação e documentação.</span></div><Field label="Deficiência"><input value={form.deficiencia} onChange={e=>set('deficiencia',e.target.value)}/></Field><Field label="Telefone"><input value={form.telefone} onChange={e=>set('telefone',e.target.value)}/></Field><Field label="E-mail"><input type="email" value={form.email} onChange={e=>set('email',e.target.value)}/></Field>
      <Field label="Nome do pai"><input value={form.pai} onChange={e=>set('pai',e.target.value)}/></Field><Field label="Nome da mãe"><input value={form.mae} onChange={e=>set('mae',e.target.value)}/></Field><Field label="Beneficiários" wide><input value={form.beneficiarios} onChange={e=>set('beneficiarios',e.target.value)}/></Field>
    </div></>
    if(step===1)return <><h3 className="section-title">Documentos e endereço residencial</h3><div className="form-grid form-grid-3">
      <Field label="RG"><input value={form.rg} onChange={e=>set('rg',e.target.value)}/></Field><Field label="Emissão RG"><input type="date" value={form.rg_emissao} onChange={e=>set('rg_emissao',e.target.value)}/></Field><Field label="Órgão emissor"><input value={form.rg_orgao} onChange={e=>set('rg_orgao',e.target.value)}/></Field>
      <Field label="CTPS"><input value={form.ctps} onChange={e=>set('ctps',e.target.value)}/></Field><Field label="Série CTPS"><input value={form.ctps_serie} onChange={e=>set('ctps_serie',e.target.value)}/></Field><Field label="UF CTPS"><input value={form.ctps_uf} onChange={e=>set('ctps_uf',e.target.value)}/></Field><Field label="Expedição CTPS"><input type="date" value={form.ctps_expedicao} onChange={e=>set('ctps_expedicao',e.target.value)}/></Field>
      <Field label="PIS"><input value={form.pis} onChange={e=>set('pis',e.target.value)}/></Field><Field label="CNH"><input value={form.cnh} onChange={e=>set('cnh',e.target.value)}/></Field><Field label="Categoria CNH"><input value={form.cnh_categoria} onChange={e=>set('cnh_categoria',e.target.value)}/></Field>
      <Field label="Título eleitoral"><input value={form.titulo_eleitor} onChange={e=>set('titulo_eleitor',e.target.value)}/></Field><Field label="Zona"><input value={form.titulo_eleitor_zona} onChange={e=>set('titulo_eleitor_zona',e.target.value)}/></Field><Field label="Seção"><input value={form.titulo_eleitor_secao} onChange={e=>set('titulo_eleitor_secao',e.target.value)}/></Field>
      <Field label="Reservista"><input value={form.certificado_reservista} onChange={e=>set('certificado_reservista',e.target.value)}/></Field><Field label="Categoria reservista"><input value={form.reservista_categoria} onChange={e=>set('reservista_categoria',e.target.value)}/></Field><Field label="CEP"><input value={form.cep} onChange={e=>set('cep',e.target.value)}/></Field>
      <Field label="Logradouro" wide><input value={form.endereco_logradouro} onChange={e=>set('endereco_logradouro',e.target.value)}/></Field><Field label="Número"><input value={form.endereco_numero} onChange={e=>set('endereco_numero',e.target.value)}/></Field><Field label="Complemento"><input value={form.endereco_complemento} onChange={e=>set('endereco_complemento',e.target.value)}/></Field>
      <Field label="Bairro"><input value={form.endereco_bairro} onChange={e=>set('endereco_bairro',e.target.value)}/></Field><Field label="Cidade"><input value={form.endereco_cidade} onChange={e=>set('endereco_cidade',e.target.value)}/></Field><Field label="UF"><input value={form.endereco_uf} onChange={e=>set('endereco_uf',e.target.value)}/></Field>
      <Field label="Endereço legado" wide hint="Mantido apenas para compatibilidade com cadastros anteriores"><input value={form.endereco} onChange={e=>set('endereco',e.target.value)}/></Field>
    </div></>
    if(step===2)return <><h3 className="section-title">Vínculo, jornada e remuneração</h3><div className="form-grid form-grid-3">
      <Field label="Empresa" required><select value={form.empresa_id} onChange={e=>set('empresa_id',e.target.value)}><option value="">Selecione</option>{companies.data?.map((item:any)=><option value={item.id} key={item.id}>{item.nome_fantasia||item.razao_social}</option>)}</select></Field>
      <Field label="Obra atual"><select value={form.obra_atual_id} onChange={e=>set('obra_atual_id',e.target.value)}><option value="">Sem obra</option>{works.data?.filter((item:any)=>!form.empresa_id||item.empresa_id===Number(form.empresa_id)).map((item:any)=><option value={item.id} key={item.id}>{item.nome}</option>)}</select></Field>
      <Field label="Cargo" required><select value={form.cargo_id} onChange={e=>chooseCargo(e.target.value)}><option value="">Selecione</option>{activeCargos.map((item:any)=><option value={item.id} key={item.id}>{item.nome}{item.cbo?` · CBO ${item.cbo}`:''}</option>)}</select></Field>
      <Field label="Admissão"><input type="date" value={form.admissao} onChange={e=>set('admissao',e.target.value)}/></Field><Field label="Salário mensal" hint="Preenchido pelo cargo"><input value={form.salario} readOnly className="input-locked"/></Field><Field label="Matrícula interna"><input value={form.matricula} onChange={e=>set('matricula',e.target.value)}/></Field>
      <Field label="Matrícula eSocial"><input value={form.matricula_esocial} onChange={e=>set('matricula_esocial',e.target.value)}/></Field><Field label="Optante FGTS"><select value={form.fgts_optante} onChange={e=>set('fgts_optante',e.target.value)}><option value="1">Sim</option><option value="0">Não</option></select></Field><Field label="Data opção FGTS"><input type="date" value={form.fgts_opcao_em} onChange={e=>set('fgts_opcao_em',e.target.value)}/></Field>
      <Field label="Experiência (dias)"><input type="number" min="1" max="90" value={form.experiencia_dias} onChange={e=>set('experiencia_dias',e.target.value)}/></Field><Field label="Término da experiência"><input type="date" value={form.experiencia_fim} onChange={e=>set('experiencia_fim',e.target.value)}/></Field><Field label="Departamento"><input value={form.departamento} onChange={e=>set('departamento',e.target.value)}/></Field>
      <Field label="Entrada"><input type="time" value={form.jornada_inicio} onChange={e=>set('jornada_inicio',e.target.value)}/></Field><Field label="Início intervalo"><input type="time" value={form.intervalo_inicio} onChange={e=>set('intervalo_inicio',e.target.value)}/></Field><Field label="Fim intervalo"><input type="time" value={form.intervalo_fim} onChange={e=>set('intervalo_fim',e.target.value)}/></Field><Field label="Saída"><input type="time" value={form.jornada_fim} onChange={e=>set('jornada_fim',e.target.value)}/></Field>
    </div>{chosenCargo&&<div className="role-preview"><div><strong>{chosenCargo.nome}</strong><span>Salário-base {brl(chosenCargo.salario_base_centavos)}</span></div>{chosenBenefits.map((link:any)=><span className="benefit-chip" key={link.id}>{link.benefit?.nome}: {brl(link.valor_centavos)}</span>)}</div>}</>
    if(step===3)return <><h3 className="section-title">Benefícios, pagamento e equipamentos</h3><div className="notice fixed-benefit-notice">Benefícios fixos são herdados do cargo e permanecem configuráveis por empresa. O kit de EPI usado no documento é filtrado pelo perfil empresa/cargo quando houver configuração; sem perfil, permanecem os EPIs selecionados manualmente.</div><div className="form-grid form-grid-3" style={{marginTop:16}}>
      <Field label="Vale-transporte"><select value={form.vale_transporte_opcao} onChange={e=>set('vale_transporte_opcao',e.target.value)}><option value="1">Opta pelo benefício</option><option value="0">Não opta</option></select></Field><Field label="Banco"><input value={form.banco} onChange={e=>set('banco',e.target.value)}/></Field><Field label="Agência"><input value={form.agencia} onChange={e=>set('agencia',e.target.value)}/></Field><Field label="Conta"><input value={form.conta_bancaria} onChange={e=>set('conta_bancaria',e.target.value)}/></Field><Field label="Chave PIX"><input value={form.pix} onChange={e=>set('pix',e.target.value)}/></Field><Field label="Trajeto e tarifas" wide><textarea value={form.vale_transporte_detalhes} onChange={e=>set('vale_transporte_detalhes',e.target.value)}/></Field>
    </div><h3 className="section-title" style={{marginTop:20}}>EPIs entregues na admissão</h3><div className="doc-grid">{epis.data?.map((item:any)=><label className="doc-option" key={item.id}><input type="checkbox" checked={form.selectedEpis.includes(item.id)} onChange={e=>set('selectedEpis',e.target.checked?[...form.selectedEpis,item.id]:form.selectedEpis.filter((epiId:number)=>epiId!==item.id))}/><span><b>{item.nome}</b><small style={{display:'block',color:'#7d8797'}}>C.A. {item.ca||'não informado'}</small></span></label>)}</div></>
    return result?<div className="state" style={{minHeight:430}}><CheckCircle2 style={{color:'#159a76'}}/><strong>Dossiê gerado com sucesso</strong><p>{result.generated.length} documentos foram gravados e consolidados no dossiê de admissão.</p><div style={{display:'flex',gap:8}}><Button variant="secondary" icon={<FolderOpen size={16}/>} onClick={()=>window.fluxoDre.documentos.openFolder()}>Abrir pasta</Button><Button icon={<Printer size={16}/>} onClick={()=>window.fluxoDre.documentos.open(result.dossier)}>Abrir dossiê</Button></div></div>:<><h3 className="section-title">Selecione os documentos para gerar</h3><div className="notice">O conjunto padrão comercial é neutro e pode ser substituído por modelos próprios da empresa. Carta sindical continua opcional e deve ser revisada conforme o instrumento coletivo aplicável.</div><div className="doc-grid" style={{marginTop:13}}>{docs.map(([key,label])=><label className="doc-option" key={key}><input type="checkbox" checked={form.selectedDocs.includes(key)} onChange={e=>set('selectedDocs',e.target.checked?[...form.selectedDocs,key]:form.selectedDocs.filter((item:string)=>item!==key))}/><FileSignature size={17}/><span><b>{label}</b><small style={{display:'block',color:'#7d8797'}}>{key==='carta_sindical'?'Opcional / configurável':'Modelo comercial configurável'}</small></span></label>)}</div></>
  },[step,form,companies.data,works.data,catalog.data,epis.data,result])

  return <><PageHeader title={id?'Documentos do funcionário':'Registro funcionário'} description="Cadastro admissional completo, com validação por documento e modelos configuráveis por empresa." actions={form.id&&<Button variant="secondary" icon={<Save size={16}/>} onClick={saveEmployee}>Salvar alterações</Button>}/><Card><div className="progress"><div style={{width:`${(step+1)/steps.length*100}%`}}/></div><div className="wizard"><aside className="wizard-steps">{steps.map((label,index)=><div key={label} className={`wizard-step ${index===step?'active':''}`}><b>{index+1}</b><span>{label}</span></div>)}</aside><section className="wizard-content"><div className="modal-body">{companies.loading||catalog.loading?<Loading/>:content}{message&&<div className="notice" style={{marginTop:14}}>{message}</div>}</div><div className="modal-footer"><Button variant="secondary" icon={<ArrowLeft size={16}/>} disabled={step===0||saving} onClick={()=>setStep(Math.max(0,step-1))}>Voltar</Button>{step<4?<Button icon={<ArrowRight size={16}/>} disabled={saving} onClick={next}>Continuar</Button>:<Button icon={<FileSignature size={16}/>} disabled={saving||!!result} onClick={generate}>{saving?'Gerando...':'Salvar e gerar documentos'}</Button>}</div></section></div></Card></>
}
