import { Form } from '../components/ui'
import { CopyPlus, FilePenLine, FolderUp, Plus, Settings2, ShieldCheck, Trash2 } from 'lucide-react'
import { FormEvent, useMemo, useRef, useState } from 'react'
import { ErrorState, Button, Card, Empty, Field, FormActions, Loading, Modal, PageHeader, Status } from '../components/ui'
import { useAsync } from '../hooks/useAsync'
import TemplateEditor from '../components/TemplateEditor'
import { humanizeHrDocumentKey } from '../utils/hr'

const fields=['nome_funcionario','cpf','rg','rg_emissao','rg_orgao','ctps','ctps_serie','ctps_uf','ctps_expedicao','pis','cargo','cbo','admissao','salario','matricula','matricula_esocial','fgts_opcao_em','endereco_funcionario','endereco_logradouro','endereco_numero','endereco_complemento','endereco_bairro','endereco_cidade','endereco_uf','cep','empresa','cnpj','endereco_empresa','data_hoje']
const fieldLabel:Record<string,string>={nome_funcionario:'Nome do funcionário',cpf:'CPF',rg:'RG',rg_emissao:'Emissão RG',rg_orgao:'Órgão RG',ctps:'CTPS',ctps_serie:'Série CTPS',ctps_uf:'UF CTPS',ctps_expedicao:'Expedição CTPS',pis:'PIS',cargo:'Cargo',cbo:'CBO',admissao:'Admissão',salario:'Salário',matricula:'Matrícula',matricula_esocial:'Matrícula eSocial',fgts_opcao_em:'Data FGTS',endereco_funcionario:'Endereço completo',endereco_logradouro:'Logradouro',endereco_numero:'Número',endereco_complemento:'Complemento',endereco_bairro:'Bairro',endereco_cidade:'Cidade',endereco_uf:'UF',cep:'CEP',empresa:'Empresa',cnpj:'CNPJ',endereco_empresa:'Endereço da empresa',data_hoje:'Data de hoje'}
const documentKeys=['contrato_experiencia','ficha_registro','ordem_servico','vale_transporte','ficha_epi','carta_sindical']
const blank={chave:'contrato_experiencia',nome:'',conteudo_html:'<p>Entre <b>{{empresa}}</b>, CNPJ {{cnpj}}, e <b>{{nome_funcionario}}</b>, CPF {{cpf}}, fica firmado o presente documento.</p><p>Função: {{cargo}}. Admissão: {{admissao}}. Salário: {{salario}}.</p>',ativo:1,arquivo_origem:''}

function previewDocument(content:string){
  const safe=String(content||'').replace(/<script\b[^>]*>[\s\S]*?<\/script\s*>/gi,'')
  const highlighter=`<script>document.querySelectorAll('body *').forEach(function(node){Array.from(node.childNodes).filter(function(child){return child.nodeType===3}).forEach(function(text){var fragment=document.createDocumentFragment(),parts=text.nodeValue.split(/(\\{\\{(?:manual:[^}]+|[a-z_]+)\\}\\})/gi);if(parts.length>1){parts.forEach(function(part){if(/^\\{\\{(?:manual:[^}]+|[a-z_]+)\\}\\}$/i.test(part)){var mark=document.createElement('mark');mark.textContent=part;fragment.appendChild(mark)}else{fragment.appendChild(document.createTextNode(part))}});text.replaceWith(fragment)}})})<\/script>`
  const csp=`<meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:">`,style='<style>body{font-family:Arial,sans-serif;color:#111;padding:18px;line-height:1.45;font-size:13px}mark{background:#fff1a8;color:#503b00;padding:1px 3px;border-radius:3px;font-weight:700}table{border-collapse:collapse;width:100%}td,th{border:1px solid #aaa;padding:5px}</style>'
  return /<html/i.test(safe)?safe.replace(/<head[^>]*>/i,(head)=>`${head}${csp}${style}`).replace(/<\/body>/i,`${highlighter}</body>`):`<!doctype html><html><head>${csp}${style}</head><body>${safe}${highlighter}</body></html>`
}

export default function HrTemplatesPage(){
  const templates=useAsync<any>(()=>window.fluxoDre.documentos.templates(),[]), companies=useAsync(()=>window.fluxoDre.empresas.list(),[]), catalog=useAsync(()=>window.fluxoDre.catalogo.list(),[]), epis=useAsync(()=>window.fluxoDre.epis.list(),[])
  const [advanced,setAdvanced]=useState(false),[saving,setSaving]=useState(false),[message,setMessage]=useState('')
  const [modal,setModal]=useState(false),[form,setForm]=useState<any>(blank),[loadingFile,setLoadingFile]=useState(false),[manualLabel,setManualLabel]=useState('')
  const [companyId,setCompanyId]=useState(''),[cargoId,setCargoId]=useState(''),[profileEdit,setProfileEdit]=useState<any>(null),[epiForm,setEpiForm]=useState<any>({epi_id:'',quantidade_texto:'01'})
  const mutation=useRef(false)
  const runMutation=async(action:()=>Promise<unknown>,success:string)=>{if(mutation.current)return false;mutation.current=true;setSaving(true);setMessage('');try{await action();await templates.reload();setMessage(success);return true}catch(e:any){setMessage(e.message);return false}finally{mutation.current=false;setSaving(false)}}
  const editorRef=useRef<HTMLTextAreaElement>(null)
  const data=templates.data||{}, templateList:any[]=data.templates||[], profiles:any[]=data.companyProfiles||[], epiKits:any[]=data.epiKits||[], documents:any[]=data.documents||documentKeys.map(key=>({key,title:key.replaceAll('_',' ')}))
  const companyProfiles=profiles.filter(item=>String(item.empresa_id)===String(companyId)), selectedKit=epiKits.filter(item=>String(item.empresa_id)===String(companyId)&&String(item.cargo_id)===String(cargoId))
  const usedFields=useMemo(()=>[...new Set(Array.from(String(form.conteudo_html||'').matchAll(/\{\{((?:manual:[^}]+)|[a-z_]+)\}\}/gi),(match)=>match[1].toLowerCase()))],[form.conteudo_html])
  const open=(item?:any)=>{if(item?.origem==='padrao')setForm({...blank,chave:item.chave,nome:item.nome.replace(' (padrão comercial v2)',' - personalizado')});else setForm(item?{...item}:blank);setModal(true)}
  const importLocal=async()=>{setLoadingFile(true);try{const imported=await window.fluxoDre.documentos.chooseLocalTemplate();if(imported)setForm({...form,...imported,nome:form.nome||imported.nome})}catch(e:any){setMessage(e.message)}finally{setLoadingFile(false)}}
  const insertManualField=()=>{const label=manualLabel.trim();if(!label)return;const editor=editorRef.current,marker=`{{manual:${label}}}`,start=editor?.selectionStart??String(form.conteudo_html).length,end=editor?.selectionEnd??start,content=String(form.conteudo_html||'');setForm({...form,conteudo_html:`${content.slice(0,start)}${marker}${content.slice(end)}`});setManualLabel('');requestAnimationFrame(()=>{editor?.focus();editor?.setSelectionRange(start+marker.length,start+marker.length)})}
  const save=async(event:FormEvent)=>{event.preventDefault();if(saving)return;setSaving(true);setMessage('');try{await window.fluxoDre.documentos.saveTemplate({...form,ativo:Number(form.ativo)});setModal(false);await templates.reload();setMessage('Modelo salvo.')}catch(e:any){setMessage(e.message)}finally{setSaving(false)}}
  const select=async(item:any)=>runMutation(()=>window.fluxoDre.documentos.setDefaultTemplate({chave:item.chave,modelo_id:item.id}),'Modelo padrão atualizado.')
  const saveProfile=async(profile:any)=>{if(!companyId)return false;return runMutation(()=>window.fluxoDre.documentos.saveTemplate({kind:'company-profile',empresa_id:Number(companyId),documento_key:profile.documento_key,ativo:profile.ativo===0?0:1,obrigatorio:profile.obrigatorio?1:0,modelo_id:profile.modelo_id||null,titulo_customizado:profile.titulo_customizado||null,configuracao:profile.configuracao||{}}),'Regra da empresa salva.')}
  const toggleProfile=async(doc:any,field:'ativo'|'obrigatorio')=>{if(!companyId)return;const current=companyProfiles.find(item=>item.documento_key===doc.key)||{documento_key:doc.key,ativo:1,obrigatorio:doc.optional?0:1,configuracao:{}};await saveProfile({...current,[field]:field==='ativo'?(current.ativo===0?1:0):(current.obrigatorio?0:1)})}
  const openProfile=(doc:any)=>{const current=companyProfiles.find(item=>item.documento_key===doc.key)||{documento_key:doc.key,ativo:1,obrigatorio:doc.optional?0:1,titulo_customizado:'',configuracao:{}};setProfileEdit({...current,configuracao:{...(current.configuracao||{})}})}
  const addEpi=async()=>{if(!companyId||!cargoId||!epiForm.epi_id)return;if(await runMutation(()=>window.fluxoDre.documentos.saveTemplate({kind:'epi-kit',empresa_id:Number(companyId),cargo_id:Number(cargoId),epi_id:Number(epiForm.epi_id),quantidade_texto:epiForm.quantidade_texto||'01',ativo:1}),'EPI adicionado ao kit.'))setEpiForm({epi_id:'',quantidade_texto:'01'})}
  const removeEpi=async(item:any)=>runMutation(()=>window.fluxoDre.documentos.saveTemplate({kind:'epi-kit-remove',empresa_id:item.empresa_id,cargo_id:item.cargo_id,epi_id:item.epi_id}),'EPI removido do kit.')

  if(templates.error)return <ErrorState error={templates.error} retry={templates.reload}/>
  if(companies.error)return <ErrorState error={companies.error} retry={companies.reload}/>
  if(catalog.error)return <ErrorState error={catalog.error} retry={catalog.reload}/>
  if(epis.error)return <ErrorState error={epis.error} retry={epis.reload}/>
  return <>{message&&!modal&&<p role="status">{message}</p>}<PageHeader title="RH · Modelos e regras admissionais" description="Configure modelos de documentos, regras admissionais por empresa e kits de EPI por cargo." actions={<Button icon={<Plus size={16}/>} onClick={()=>open()}>Novo modelo</Button>}/>
    <Card><h3 className="section-title">Política admissional por empresa</h3><div className="form-grid form-grid-3"><Field label="Empresa"><select value={companyId} onChange={e=>{setCompanyId(e.target.value);setCargoId('')}}><option value="">Selecione</option>{companies.data?.map((item:any)=><option value={item.id} key={item.id}>{item.nome_fantasia||item.razao_social}</option>)}</select></Field></div>{companyId?<div className="table-wrap" style={{marginTop:14}}><table className="data-table"><thead><tr><th>Documento</th><th>Ativo</th><th>Obrigatório</th><th>Modelo</th><th/></tr></thead><tbody>{documents.map((doc:any)=>{const profile=companyProfiles.find(item=>item.documento_key===doc.key),active=profile?Number(profile.ativo)!==0:true,required=profile?Boolean(profile.obrigatorio):!doc.optional;return <tr key={doc.key}><td><strong>{profile?.titulo_customizado||doc.title}</strong>{doc.optional&&<small style={{display:'block',color:'var(--muted)'}}>Opcional no padrão comercial</small>}</td><td><Button variant="ghost" disabled={saving} onClick={()=>toggleProfile(doc,'ativo')}><Status value={active?'ativo':'inativo'}/></Button></td><td><Button variant="ghost" disabled={saving} onClick={()=>toggleProfile(doc,'obrigatorio')}><Status value={required?'ativo':'inativo'}/></Button></td><td>{profile?.modelo_id||'Padrão comercial v2'}</td><td><Button variant="secondary" icon={<Settings2 size={15}/>} onClick={()=>openProfile(doc)}>Configurar</Button></td></tr>})}</tbody></table></div>:<div className="notice" style={{marginTop:12}}>Selecione uma empresa para personalizar quais documentos entram no dossiê. Sem configuração, o sistema usa o conjunto padrão comercial e mantém a carta sindical opcional.</div>}</Card>

    <Card><h3 className="section-title">Kit de EPI por empresa e cargo</h3><div className="form-grid form-grid-3"><Field label="Empresa"><select value={companyId} onChange={e=>{setCompanyId(e.target.value);setCargoId('')}}><option value="">Selecione</option>{companies.data?.map((item:any)=><option value={item.id} key={item.id}>{item.nome_fantasia||item.razao_social}</option>)}</select></Field><Field label="Cargo"><select value={cargoId} onChange={e=>setCargoId(e.target.value)}><option value="">Selecione</option>{catalog.data?.cargos.filter((item:any)=>item.ativo).map((item:any)=><option value={item.id} key={item.id}>{item.nome}</option>)}</select></Field></div>{companyId&&cargoId?<><div className="form-grid form-grid-3" style={{marginTop:14}}><Field label="EPI"><select value={epiForm.epi_id} onChange={e=>setEpiForm({...epiForm,epi_id:e.target.value})}><option value="">Selecione</option>{epis.data?.filter((item:any)=>item.ativo).map((item:any)=><option value={item.id} key={item.id}>{item.nome}{item.ca?` · CA ${item.ca}`:''}</option>)}</select></Field><Field label="Quantidade / unidade"><input value={epiForm.quantidade_texto} onChange={e=>setEpiForm({...epiForm,quantidade_texto:e.target.value})} placeholder="01, 02, PT..."/></Field><Field label="Adicionar"><Button type="button" icon={<ShieldCheck size={15}/>} disabled={saving} onClick={addEpi}>Adicionar ao kit</Button></Field></div>{selectedKit.length?<div className="table-wrap" style={{marginTop:12}}><table className="data-table"><thead><tr><th>EPI</th><th>C.A.</th><th>Quantidade</th><th/></tr></thead><tbody>{selectedKit.map((item:any)=><tr key={`${item.empresa_id}-${item.cargo_id}-${item.epi_id}`}><td>{item.epi_nome}</td><td>{item.ca||'—'}</td><td>{item.quantidade_texto}</td><td><button className="icon-button" onClick={()=>removeEpi(item)}><Trash2 size={15}/></button></td></tr>)}</tbody></table></div>:<div className="notice" style={{marginTop:12}}>Nenhum kit específico. Nesse caso a ficha de EPI usa as entregas registradas manualmente para o colaborador.</div>}</>:<div className="notice" style={{marginTop:12}}>Selecione empresa e cargo para configurar o kit de EPI. Cada empresa mantém suas próprias regras e quantidades.</div>}</Card>

    <Card><h3 className="section-title">Biblioteca de modelos</h3>{templates.loading?<Loading/>:templateList.length?<div className="table-wrap"><table className="data-table"><thead><tr><th>Documento</th><th>Modelo</th><th>Origem</th><th>Status</th><th>Uso padrão</th><th/></tr></thead><tbody>{templateList.map((item:any)=><tr key={item.id}><td>{humanizeHrDocumentKey(item.chave)}</td><td><strong>{item.nome}</strong>{item.arquivo_origem&&<small style={{display:'block'}}>{item.arquivo_origem}</small>}</td><td>{item.origem==='padrao'?'Padrão comercial':item.arquivo_origem?'Arquivo local importado':'Personalizado'}</td><td><Status value={item.ativo?'ativo':'inativo'}/></td><td>{item.selecionado?<Status value="ativo"/>:<Button variant="ghost" disabled={saving||!item.ativo} onClick={()=>select(item)}>Usar este</Button>}</td><td><Button variant="secondary" icon={item.origem==='padrao'?<CopyPlus size={15}/>:<FilePenLine size={15}/>} onClick={()=>open(item)}>{item.origem==='padrao'?'Criar cópia':'Editar'}</Button></td></tr>)}</tbody></table></div>:<Empty title="Nenhum modelo disponível"/>}</Card>

    <Modal open={!!profileEdit} title="Configuração do documento na empresa" onClose={()=>setProfileEdit(null)} size="lg">{profileEdit&&<Form noValidate onSubmit={async e=>{e.preventDefault();if(await saveProfile(profileEdit))setProfileEdit(null)}}><div className="modal-body form-grid"><Field label="Título customizado" wide><input value={profileEdit.titulo_customizado||''} onChange={e=>setProfileEdit({...profileEdit,titulo_customizado:e.target.value})}/></Field>{profileEdit.documento_key==='ordem_servico'&&<><Field label="Atividades" wide><textarea className="resize-none" value={profileEdit.configuracao?.atividades||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,atividades:e.target.value}})}/></Field><Field label="Riscos" wide><textarea className="resize-none" value={profileEdit.configuracao?.riscos||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,riscos:e.target.value}})}/></Field><Field label="Medidas preventivas" wide><textarea className="resize-none" value={profileEdit.configuracao?.medidas||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,medidas:e.target.value}})}/></Field><Field label="Orientação de EPI" wide><textarea className="resize-none" value={profileEdit.configuracao?.epis_orientacao||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,epis_orientacao:e.target.value}})}/></Field><Field label="Treinamentos / requisitos" wide><textarea className="resize-none" value={profileEdit.configuracao?.treinamentos||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,treinamentos:e.target.value}})}/></Field></>}{profileEdit.documento_key==='carta_sindical'&&<><Field label="Entidade sindical"><input value={profileEdit.configuracao?.sindicato_nome||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,sindicato_nome:e.target.value}})}/></Field><Field label="Endereço da entidade"><input value={profileEdit.configuracao?.sindicato_endereco||''} onChange={e=>setProfileEdit({...profileEdit,configuracao:{...profileEdit.configuracao,sindicato_endereco:e.target.value}})}/></Field><div className="notice field-wide">A carta permanece opcional por padrão. O texto deve ser conferido conforme convenção coletiva, prazo e regras aplicáveis à empresa.</div></>}</div>{message&&<p role="alert">{message}</p>}<FormActions loading={saving} onCancel={()=>{if(!saving)setProfileEdit(null)}} submitLabel="Salvar regra"/></Form>}</Modal>

    <Modal open={modal} title={form.id?'Editar modelo do cliente':'Novo modelo do cliente'} onClose={()=>setModal(false)} size="xl"><Form noValidate onSubmit={save}><div className="modal-body form-grid"><Field label="Tipo de documento"><select value={form.chave} onChange={e=>setForm({...form,chave:e.target.value})}>{documentKeys.map(item=><option value={item} key={item}>{humanizeHrDocumentKey(item)}</option>)}</select></Field><Field label="Nome do modelo" required><input required value={form.nome} onChange={e=>setForm({...form,nome:e.target.value})}/></Field><Field label="Status"><select value={form.ativo} onChange={e=>setForm({...form,ativo:e.target.value})}><option value="1">Ativo</option><option value="0">Inativo</option></select></Field><Field label="Modelo local"><Button type="button" variant="secondary" icon={<FolderUp size={15}/>} onClick={importLocal} disabled={loadingFile}>{loadingFile?'Abrindo...':'Importar HTML, HTM ou TXT'}</Button>{form.arquivo_origem&&<small>Fonte: {form.arquivo_origem}</small>}</Field><div className="field-wide"><Button type="button" variant="secondary" onClick={()=>setAdvanced(v=>!v)}>{advanced?'Voltar à edição visual':'Editar HTML (avançado)'}</Button></div>{!advanced?<TemplateEditor value={form.conteudo_html} onChange={html=>setForm({...form,conteudo_html:html})}/>:<><Field label="Conteúdo HTML" wide hint="Use {{campo}} para inserir dados automaticamente."><textarea ref={editorRef} className="resize-none template-editor" required value={form.conteudo_html} onChange={e=>setForm({...form,conteudo_html:e.target.value})}/></Field></>}<Field label="Campo manual" wide><div className="template-manual-insert"><input value={manualLabel} placeholder="Ex.: assinatura do responsável" onChange={e=>setManualLabel(e.target.value)}/><Button type="button" variant="secondary" onClick={insertManualField}>Inserir no cursor</Button></div></Field><div className="field field-wide template-preview-panel"><span>Prévia do modelo</span><iframe title="Prévia do modelo" sandbox="" srcDoc={previewDocument(form.conteudo_html)}/><div className="template-fields"><strong>Campos encontrados:</strong>{usedFields.length?usedFields.map(field=><span key={field}>{`{{${field}}}`} · {field.startsWith('manual:')?`Preencher manualmente: ${field.slice(7)}`:fieldLabel[field]||'Campo não reconhecido'}</span>):<em>Adicione campos como {'{{nome_funcionario}}'}.</em>}</div><small>Campos disponíveis: {fields.map(field=>`{{${field}}}`).join(', ')}</small></div></div>{message&&<p role="alert">{message}</p>}<FormActions loading={saving} onCancel={()=>setModal(false)} submitLabel="Salvar modelo"/></Form></Modal>
  </>
}
